src/reporter/apps/main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
]

src/reporter/apps/tapis/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "tapis"
urlpatterns = [
    path("", views.index, name="index"),
    path("tenants/", views.tenants, name="tenants"),
    path("trainings/", views.trainings, name="trainings"),
    path("gateways/", views.gateways, name="gateways"),
    path("gateways/<str:tenant>", views.tenant_gateways, name="tenant_gateways"),
    path("github/", views.github, name="github"),
    path("papers/", views.papers, name="papers"),
    path("streams/", views.streams, name="streams"),
    path("splunk/", views.splunk, name="splunk"),
    path("jobs/", views.jobs, name="jobs"),
    path("tapis/", views.tapis, name="tapis"),
]

src/reporter/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reporter.apps.main.urls")),
    path("auth/", include("reporter.apps.tapisauth.urls")),
    path("jupyterhub/", include("reporter.apps.jupyterhub.urls")),
    path("tapis/", include("reporter.apps.tapis.urls")),
]

src/reporter/apps/tapis/models.py
from django.db import models

# Create your models here.


class Paper(models.Model):
    title = models.TextField()
    primary_author = models.CharField(max_length=255)
    publication_source = models.TextField()
    publication_date = models.IntegerField()
    co_authors = models.TextField()
    citation_url = models.TextField()
    citations = models.IntegerField()

    class Meta:
        unique_together = ["title", "primary_author"]

    def savepaper(self):
        self.save()

    def __str__(self):
        return self.title + " " + self.primary_author


class Training(models.Model):
    name = models.TextField()
    forum = models.TextField()
    date = models.DateField()
    num_attendees = models.IntegerField()


# Holds data pertaining to db data for all of tapis
class TapisInfo(models.Model):
    tenant = models.CharField(max_length=255, primary_key=True)
    num_tokens = models.IntegerField()
    num_unique_users = models.IntegerField()
    num_ctr_apps = models.IntegerField()


# Holds data pertaining to jobs db query
class JobsData(models.Model):
    avg_daily_jobs = models.IntegerField()
    dev_daily_jobs = models.CharField(max_length=50)
    total_jobs = models.IntegerField()
    num_using_smart_scheduling = models.IntegerField()


class TenantServiceUsage(models.Model):
    log_date = models.DateField()
    start_time = models.CharField(max_length=10)
    end_time = models.CharField(max_length=10)
    tenant = models.CharField(max_length=100)
    service = models.CharField(max_length=50)
    log_count = models.IntegerField()

    class Meta:
        unique_together = ["log_date", "start_time", "end_time", "tenant", "service"]

    def savetenantserviceusage(self):
        self.save()

    def __str__(self):
        return f"{self.log_date} {self.start_time}-{self.end_time} \
            {self.tenant} {self.service} {self.log_count}"

src/reporter/apps/tapis/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.db.models import Q
from django.conf import settings
from django.contrib.auth.decorators import login_required
import ast
import logging
import random
import requests
from .models import Paper, TenantServiceUsage, JobsData, TapisInfo

logger = logging.getLogger(__name__)

# Create your views here.
from django.http import HttpResponse


@login_required
def index(request):
    if request.method == "GET":
        template = loader.get_template("tapis/index.html")

        context = {
            "error": False,
            "tapisdocs": "https://tapis.readthedocs.io/en/latest/technical/index.html",
        }

        return HttpResponse(template.render(context, request))


@login_required
def tenants(request):
    if request.method == "GET":
        template = loader.get_template("tapis/tenants.html")

        context = {
            "error": False,
        }

        try:
            tenants_call = requests.get("https://tacc.tapis.io/v3/tenants")
            tenants_info = tenants_call.json()["result"]

            tenants = []
            for tenant_info in tenants_info:
                owner = tenant_info["owner"]
                owner_call = requests.get(
                    f"https://tacc.tapis.io/v3/tenants/owners/{owner}"
                )
                owner_info = owner_call.json()["result"]

                tenant = build_tenant_model(tenant_info, owner_info)

                tenants.append(tenant)
        except Exception as e:
            context["error"] = True
            context["message"] = e
        else:
            context["tenants"] = tenants
            context["tenant_count"] = len(tenants)

        return HttpResponse(template.render(context, request))


@login_required
def trainings(request):
    if request.method == "GET":
        logger.debug(f"In {request.method} method of trainings")
        template = loader.get_template("tapis/training.html")

        context = {
            "error": False,
        }

        try:
            trainings_url = requests.get(
                "https://raw.githubusercontent.com/tapis-project/tapis-reporting/main/tapis_training.json"
            )

            trainings_data = trainings_url.json()
            context["trainings_data"] = trainings_data
        except Exception as e:
            logger.error(f"ERROR: {e}")
            context["error"] = True
            context["message"] = e

        return HttpResponse(template.render(context, request))


@login_required
def gateways(request):
    if request.method == "GET":
        logger.debug(f"In {request.method} method of gateways")
        template = loader.get_template("tapis/gateways.html")

        context = {
            "error": False,
        }

        try:
            # load gateways file data
            gateways_data = get_gateways_data()
            tenants = []
            for gateway in gateways_data:
                tenants.append(gateway["tenant"])

            tenants = set(tenants)
            context["tenants"] = tenants

            # get number of gateways
            num_gateways = len(gateways_data)

            # misc data
            oldest_gateway = get_oldest_gateway(gateways_data)

            context["gateways_data"] = gateways_data
            context["num_gateways"] = num_gateways
            context["oldest_gateway"] = oldest_gateway["release_year"]

        except Exception as e:
            logger.error(f"ERROR: {e}")
            context["error"] = True
            context["message"] = e

        return HttpResponse(template.render(context, request))

    elif request.method == "POST":
        logger.debug(f"In {request.method} method of gateways")
        template = loader.get_template("tapis/gateways.html")

        context = {
            "error": False,
        }

        tenant = request.POST.get("tenant")
        if "tenants_gateways" in request.POST:
            return redirect("tapis:tenant_gateways", tenant=tenant)


@login_required
def tenant_gateways(request, tenant):
    if request.method == "GET":
        logger.debug(f"In {request.method} method of tenant gateways")
        template = loader.get_template("tapis/tenant_gateways.html")

        context = {"error": False, "tenant": tenant}

        try:
            tenant_gateways = get_gateways_for_tenant(tenant)
            context["tenant_gateways"] = tenant_gateways
            context["gateway_count"] = len(tenant_gateways)

            oldest_gateway = get_oldest_gateway(tenant_gateways)
            latest_gateway = get_latest_gateway(tenant_gateways)
            context["oldest_gateway"] = oldest_gateway["release_year"]
            context["latest_gateway"] = latest_gateway["release_year"]

        except Exception as e:
            logger.error(f"ERROR: {e}")
            context["error"] = True
            context["message"] = e

        return HttpResponse(template.render(context, request))


@login_required
def github(request):
    if request.method == "GET":
        logger.debug(f"In {request.method} method of github")
        template = loader.get_template("tapis/github.html")

        context = {"error": False}

        repos = get_repos("tapis-project")

        context["repos"] = repos

        return HttpResponse(template.render(context, request))


@login_required
def papers(request):
    if request.method == "GET":
        logger.debug(f"In {request.method} method of papers")
        template = loader.get_template("tapis/papers.html")

        context = {"error": False}

        try:
            tapis_papers = load_tapis_papers()
            logger.error(f"tapis papers in papers html: {tapis_papers}")
            context["tapis_papers"] = tapis_papers

        except Exception as e:
            context["error"] = True
            context["message"] = e

        return HttpResponse(template.render(context, request))

    elif request.method == "POST":
        logger.debug(f"In {request.method} method of papers")

        context = {"error": False}

        return redirect("tapis:add_paper")


@login_required
def add_paper(request):
    if request.method == "GET":
        logger.debug(f"In {request.method} method of add_paper")
        template = loader.get_template("tapis/add_paper.html")

        context = {"error": False}

        return HttpResponse(template.render(context, request))

    elif request.method == "POST":
        logger.debug(f"In {request.method} method of add_paper")

        context = {"error": False}

        paper_data = build_paper_data(request.POST)
        create_paper(paper_data)

        return redirect("tapis:paper")


@login_required
def streams(request):
    if request.method == "GET":
        logger.debug(f"In {request.method} method of streams")
        template = loader.get_template("tapis/streams.html")

        context = {"error": False}

        try:
            streams_data = get_streams_data()
            context["streams_data"] = streams_data

        except Exception as e:
            context["error"] = True
            context["message"] = e

        return HttpResponse(template.render(context, request))


@login_required
def jobs(request):
    if request.method == "GET":
        logger.debug(f"In {request.method} method of jobs")
        template = loader.get_template("tapis/jobs.html")

        context = {
            "error": False,
        }

        try:
            # load gateways file data
            jobs_data = get_jobs_data()
            context["jobs_data"] = jobs_data
        except Exception as e:
            logger.error(f"Error fetching jobs data: {e}")
        
        return HttpResponse(template.render(context, request))


@login_required
def tapis(request):
    if request.method == "GET":
        logger.debug(f"In {request.method} method of tapis")
        template = loader.get_template("tapis/tapis.html")

        context = {"error": False}

        try:
            # load gateways file data
            tapis_data = get_tapis_data()

            context["tenants"] = tapis_data["tenants"]
            context["num_tokens"] = tapis_data["num_tokens"]
            context["num_unique_users"] = tapis_data["num_unique_users"]
            context["num_ctr_apps"] = tapis_data["num_ctr_apps"]
        except Exception as e:
            logger.error(f"Error fetching tapis data: {e}")

        return HttpResponse(template.render(context, request))

    elif request.method == "POST":
        logger.debug(f"In {request.method} method of tapis")
        template = loader.get_template("tapis/tapis.html")

        context = {"error": False}

        tenant = request.POST.get("tenant")
        try:
            tenant_data = get_tenant_data(tenant)

            context["tenant_queried"] = True
            context["tenant"] = tenant
            context["num_tokens"] = tenant_data.num_tokens
            context["num_unique_users"] = tenant_data.num_unique_users
            context["num_ctr_apps"] = tenant_data.num_ctr_apps
        except Exception as e:
            logger.error(f"Error fetching tenant data: {e}")

        return HttpResponse(template.render(context, request))


@login_required
def splunk(request):
    if request.method == "GET":
        logger.debug(f"In {request.method} method of Splunk")
        template = loader.get_template("tapis/splunk_data_form.html")

        context = {"error": False}

        return HttpResponse(template.render(context, request))

    elif request.method == "POST":
        logger.debug(f"In {request.method} method of Splunk")

        template = loader.get_template("tapis/splunk_data.html")
        if "raw_tapis" in request.POST:
            template = loader.get_template("tapis/raw_splunk_data.html")

        context = {"error": False}

        logger.debug(request.POST)

        tenant = request.POST.get("tenant")
        service = request.POST.get("service")
        start_date = request.POST.get("start_date")

src/reporter/apps/tapis/templates/tapis/add_training.html
{% extends "base.html" %}
{% load static %}
{% block title %} Tapis {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}
<body>
{% block content %}
    <h3>
    Add New Training
    </h3>

    <form method="POST" id="new-training">{% csrf_token %}
        <div class="nice-form-group">
            <label>Training Name</label>
            <input 
                type="text"
                id="name"
                name="name"
            />
        </div>

        <div class="nice-form-group">
            <label>Forum</label>
            <input 
                type="text"
                id="forum"
                name="forum"
            />
        </div>

        <div class="nice-form-group">
            <label>Training Date</label>
            <input
                type="date"
                id="date"
                name="date"
                value="2024-01-01"
            />
        </div>

        <div class="nice-form-group">
            <label># Attendees</label>
            <input
                type="text"
                id="attendees"
                name="attendees"
            />
        </div>

        <button type="submit" class="btn btn-primary" name="submit_training">Submit</button>
    </form>
{% endblock %}
</body>

src/reporter/apps/tapis/templates/tapis/gateways.html
{% extends "base.html" %}
{% load static %}
{% block title %} Gateways {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}

<body>
{% block content %}

    <h3>Gateways Data since {{ oldest_gateway }}</h3>


    <form method="POST" id="gateways-form">{% csrf_token %}
        <select name="tenant" id="tenant">
            {% for tenant in tenants %}
                <option value={{ tenant }}>{{ tenant }}</option> 
            {% endfor %}
        </select>

        <button type="submit" class="btn btn-primary" name="tenants_gateways">View Tenant Gateway</button>
    </form>

    <table border=1 class="table">
        <thead>
            <tr>
                <th>Tenant</th>
                <th>Name</th>
                <th>URLs</th>
                <th>Year</th>
            </tr>
        </thead>
        <tbody>
            {% for gateway in gateways_data %}
                <tr>
                    <td>
                        {{ gateway.tenant }}
                    </td>
                    <td>
                        {{ gateway.name }}
                    </td>
                    <td>
                        {{ gateway.urls }}
                    </td>
                    <td>
                        {{ gateway.release_year }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
</body>

src/reporter/apps/tapis/templates/tapis/github.html
{% extends "base.html" %}
{% load static %}
{% block title %} Repositories {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}

<body>
{% block content %}

    <h3>GitHub Repository Data</h3>

    <table border=1 class="table">
        <thead>
            <tr>
                <th>Repo Owner</th>
                <th>Repo Name</th>
                <th>Year Created</th>
                <th>Total Issues</th>
            </tr>
        </thead>
        <tbody>
            {% for repo in repos %}
                <tr>
                    <td>
                        {{ repo.owner }}
                    </td>
                    <td>
                        {{ repo.name }}
                    </td>
                    <td>
                        {{ repo.year }}
                    </td>
                    <td>
                        {{ repo.total_issues }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
</body>

src/reporter/apps/tapis/templates/tapis/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Workbench {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}
{% block styles %}
  <link rel="stylesheet" href="">
  <link rel="stylesheet" href="">
{% endblock %}
<body>
{% block content %}
    <h3>
    Tapis Service Data
    </h3>
    <p>
    View how different Tapis services are utilized
    </p>
    
    <ul>
      <li><a href="{% url 'tapis:tapis' %}">Tapis Info</a></li>
      <li><a href="{% url 'tapis:tenants' %}">Tenants</a></li>
      <li><a href="{% url 'tapis:gateways' %}">Gateways</a></li>
      <li><a href="{% url 'tapis:trainings' %}">Trainings</a></li>
      <li><a href="{% url 'tapis:github' %}">GitHub</a></li>
      <li><a href="{% url 'tapis:papers' %}">Papers</a></li>
      <li><a href="{% url 'tapis:streams' %}">Streams</a></li>
      <li><a href="{% url 'tapis:splunk' %}">Splunk</a></li>
      <li><a href="{% url 'tapis:jobs' %}">Jobs</a></li>
      <li>
          Link to Tapis read the docs: <a href="{{ tapisdocs }}">{{ tapisdocs }}</a>
      </li>
    </ul>

{% endblock %}
</body>

src/reporter/apps/tapis/templates/tapis/jobs.html
{% extends "base.html" %}
{% load static %}
{% block title %} Gateways {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}

<body>
{% block content %}

    <h3>Jobs Data for TACC</h3>

    <h4>
        Total Number of Jobs Ran: {{ jobs_data.total_jobs }}
    </h4>
    <h4>
        Average Daily Jobs: {{ jobs_data.avg_daily_jobs }}
    </h4>
    <h4>
        Standard Deviation of Jobs: {{ jobs_data.dev_daily_jobs }}
    </h4>
    <h4>
        Number of Jobs using Smart Scheduling: {{ jobs_data.num_using_smart_scheduling }}
    </h4>

{% endblock %}
</body>

src/reporter/apps/tapis/templates/tapis/papers.html
{% extends "base.html" %}
{% load static %}
{% block title %} Papers {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}
<head>
    <link rel="stylesheet" href="static/css/buttons.css">
</head>
<body>
{% block content %}

    <h3>Tapis Research Papers</h3>
    <form method="POST" id="new-paper">{% csrf_token %}
        <button type="submit" class="btn info" name="add-paper" style="color:blue; text-decoration:underline">+ Add Paper</button>
    </form>
    <table border=1 class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Primary Author</th>
                <th>Publication Source</th>
                <th>Publication Date</th>
                <th>Co-Authors</th>
                <th>Citations URL</th>
                <th># of Citations</th>
            </tr>
        </thead>
        <tbody>
            {% for paper in tapis_papers %}
                <tr>
                    <td>
                        {{ paper.title }}
                    </td>
                    <td>
                        {{ paper.primary_author }}
                    </td>
                    <td>
                        {{ paper.publication_source }}
                    </td>
                    <td>
                        {{ paper.publication_date }}
                    </td>
                    <td>
                        {{ paper.co_authors }}
                    </td>
                    <td>
                        <a href="{{ paper.citation_url }}">Link</a>
                    </td>
                    <td>
                        {{ paper.citations }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
</body>

src/reporter/apps/tapis/templates/tapis/raw_splunk_data.html
{% extends "base.html" %}
{% load static %}
{% block title %} Splunk {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}
<body>
{% block content %}
    <h3>{{ tenant }} Analytics</h3>
    <table border=1 class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Tenant</th>
                <th>Service</th>
                <th># of Calls</th>
            </tr>
        </thead>
        <tbody>
            {% for data in tapis_data %}
                <tr>
                    <td>
                        {{ data.date }}
                    </td>
                    <td>
                        {{ data.start_time }}
                    </td>
                    <td>
                        {{ data.end_time }}
                    </td>
                    <td>
                        {{ data.tenant }}
                    </td>
                    <td>
                        {{ data.service }}
                    </td>
                    <td>
                        {{ data.count }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <!-- <form method="POST" id="gateways-form">{% csrf_token %}
        <select name="tenant" id="tenant">
            {% for gateway in gateways_data %}
                <option value={{ gateway.tenant }}>{{ gateway.tenant }}</option> 
            {% endfor %}
        </select>

        <button type="submit" class="btn btn-primary" name="tenants_gateways">View Tenant Gateway</button>
    </form> -->
{% endblock %}
</body>

src/reporter/apps/tapis/templates/tapis/splunk_data.html
{% extends "base.html" %}
{% load static %}
{% block title %} Splunk {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'tapis/main.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>
{% block content %}
    <h3>{{ tenant }} Analytics</h3>
    <div class="main">
        <div class="menu">
            <div class="service-title">Services (dropdown)</div>
            <div class="menu-item">Graphs</div>
            <div class="menu-item">Raw Data</div>
        </div>
        <div class="raw-data-contents">
            <div class="filters">
                <div class="filter">date selector</div>
                <div class="filter">search somethin</div>
                <div class="filter">filter thing</div>
                <div class="filter">order by blah</div>
            </div>
                <div class="raw-data-display">
                <div class="graph-example">
                    <div id="container" style="width: 75%">
                        <canvas id="pie-chart"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script>
        var config = {
            type: 'pie',
            data: {
                labels: {{ labels|safe }},
                datasets: [{
                    label: 'API Count',
                    data: {{ data|safe }},
                    backgroundColor: {{ backgroundColors|safe }},
                    hoverOffset: 4
                }]
            }
        };

        window.onload = function() {
            var ctx = document.getElementById('pie-chart').getContext('2d');
            window.myPie = new Chart(ctx, config);
        };
    </script>
    <!-- <form method="POST" id="gateways-form">{% csrf_token %}
        <select name="tenant" id="tenant">
            {% for gateway in gateways_data %}
                <option value={{ gateway.tenant }}>{{ gateway.tenant }}</option> 
            {% endfor %}
        </select>

        <button type="submit" class="btn btn-primary" name="tenants_gateways">View Tenant Gateway</button>
    </form> -->
{% endblock %}
</body>

src/reporter/apps/tapis/templates/tapis/splunk_data_form.html
{% extends "base.html" %}
{% load static %}
{% block title %} Tapis {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}
<head>
    <link rel="stylesheet" href="static/css/nice-forms.css">
</head>
<body>
{% block content %}
    <h3>
    Tapis Log Data
    </h3>
    <p>
    View the activity different Tapis tenants and services
    </p>

    <form method="POST" id="post-form">{% csrf_token %}
        <div class="nice-form-group">
            <label>Tenant</label>
            <input 
                type="text"
                id="tenant"
                name="tenant"
            />
        </div>

        <div class="nice-form-group">
            <label>Service (optional)</label>
            <input 
                type="text"
                id="service"
                name="service"
            />
        </div>

        <div class="nice-form-group">
            <label>Start Date</label>
            <input
                type="date"
                id="start_date"
                name="start_date"
                value="2023-07-01"
                min="2023-07-01"
            />
        </div>

        <div class="nice-form-group">
            <label>End Date</label>
            <input
                type="date"
                id="end_date"
                name="end_date"
                value="2023-07-01"
                min="2023-07-01"
            />
        </div>

        <div class="nice-form-group">
            <label>Start Time</label>
            <input
                type="time"
                id="start_time"
                name="start_time"
                min="00:00"
                max="23:59"
            />
        </div>

        <div class="nice-form-group">
            <label>End Time</label>
            <input
                type="time"
                id="end_time"
                name="end_time"
                min="00:00"
                max="23:59"
            />
        </div>

        <button type="submit" class="btn btn-primary" name="submit_form">Get Log Data</button>
        <button type="submit" class="btn btn-primary" name="raw_tapis">View Raw Data</button>
    </form>
{% endblock %}
</body>

src/reporter/apps/tapis/templates/tapis/streams.html
{% extends "base.html" %}
{% load static %}
{% block title %} Streams {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}

<body>
{% block content %}

    <h3>Tapis Streams Data</h3>

    <table border=1 class="table">
        <thead>
            <tr>
                <th>Tenant</th>
                <th>Streaming Data Collected (TB)</th>
                <th>Number of Data Streams</th>
                <th>Number of Archives</th>
            </tr>
        </thead>
        <tbody>
            {% for stream_data in streams_data %}
                <tr>
                    <td>
                        {{ stream_data.tenant }}
                    </td>
                    <td>
                        {{ stream_data.amount_data_streamed }} TB
                    </td>
                    <td>
                        {{ stream_data.number_data_streams }}
                    </td>
                    <td>
                        {{ stream_data.number_archives_registered }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
</body>

src/reporter/apps/tapis/templates/tapis/tapis.html
{% extends "base.html" %}
{% load static %}
{% block title %} Tapis {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}

<body>
{% block content %}

    {% if tenant_queried == True %}
        <h3>Tapis Data for {{ tenant }}</h3>
    {% else %}
        <h3>Tapis Data</h3>
    {% endif %}
    

    <form method="POST" id="tapis-form">{% csrf_token %}
        <select name="tenant" id="tenant">
            {% for tenant in tenants %}
                <option value={{ tenant }}>{{ tenant }}</option> 
            {% endfor %}
        </select>

        <button type="submit" class="btn btn-primary" name="tapis_tenant">View Tenant Tapis Data</button>
    </form>

    <h4>
        Number of Tokens: {{ num_tokens }}
    </h4>
    <h4>
        Number of Unique Users: {{ num_unique_users }}
    </h4>
    <h4>
        Number of Containerized Apps: {{ num_ctr_apps }}
    </h4>

{% endblock %}
</body>

src/reporter/apps/tapis/templates/tapis/tenant_gateways.html
{% extends "base.html" %}
{% load static %}
{% block title %} Gateways {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}

<body>
{% block content %}

    <h3>Gateways Data for {{ tenant }}</h3>
    <h4>There have been {{ gateway_count }} gateways between {{ oldest_gateway }} and {{ latest_gateway }}</h4>


    <table border=1 class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>URLs</th>
                <th>Year</th>
            </tr>
        </thead>
        <tbody>
            {% for gateway in tenant_gateways %}
                <tr>
                    <td>
                        {{ gateway.name }}
                    </td>
                    <td>
                        {{ gateway.urls }}
                    </td>
                    <td>
                        {{ gateway.release_year }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}
</body>

src/reporter/apps/tapis/templates/tapis/training.html
{% extends "base.html" %}
{% load static %}
{% block title %} Gateways {% endblock %}
{% block head_extra %}
  <base href="{% url 'main:index' %}">
{% endblock %}

<body>
{% block content %}

    <h3>Training Data</h3>
    <form method="POST" id="new-training">{% csrf_token %}
        <button type="submit" class="btn info" name="add-training" style="color:blue; text-decoration:underline">+ Add Training</button>
    </form>
    <table border=1 class="table">
        <thead>
            <tr>
                <th>Training</th>
                <th>Forum</th>
                <th>Date</th>
                <th>Number of Attendees</th>
            </tr>
        </thead>
        <tbody>
            {% for training in trainings_data %}
                <tr>
                    <td>
                        {{ training.name }}
                    </td>
                    <td>
                        {{ training.forum }}
                    </td>
                    <td>
                        {{ training.date }}
                    </td>
                    <td>
                        {{ training.num_attendees }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}
</body>